name: myapp
description: Flutter Firebase Login App with Supabase Image Storage
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.8.0
  firebase_app_check: ^0.3.2
  http: ^1.2.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.3
  path: ^1.8.3
  video_player: ^2.9.1
  chewie: ^1.7.1
  video_compress: ^3.1.3
  connectivity_plus: ^5.0.1
  url_launcher: ^6.3.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  workmanager: ^0.9.0+3
  google_fonts: ^6.2.1
  agora_rtc_engine: ^6.3.2
  record: ^6.1.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true